#load "graphics.cma";;
#use "Operations.ml";;
#use "Image_magick.ml"
#use "KDTrees.ml";;
#use "LocalDynArray.ml";;
#use "PriorityQueue.ml";;
#use "Rect.ml";;
#use "RTree.ml";;
#use "CustomGraph.ml";;
#use "Collision.ml";;
#use "PartiGame.ml";;
